/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.yaml.snakeyaml)
    api(libs.com.google.auto.service.auto.service)
    api(libs.com.squareup.javapoet)
}

group = "com.forestfull.devops"
version = "1.0.5"
description = "KoLogger"
java.sourceCompatibility = JavaVersion.VERSION_1_6

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
